import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import clsx from "clsx";
import "./globals.css";
import SmoothScrolling from "./SmoothScroll";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="overflow-x-hidden">
            <body className={clsx(dmSans.className, "antialiased bg-black text-white overflow-clip")}>
                <SmoothScrolling>{children}</SmoothScrolling>
            </body>
        </html>
    );
}
